# -*- coding: utf-8 -*-
"""adfd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrYapShjBhzlnw0Mg9z7AIqk44nk7UkY
"""

!kaggle datasets download -d triciaestella/gender-balanced-audio-deepfake-dataset

!unzip gender-balanced-audio-deepfake-dataset.zip -d gender_balanced_audio_data

import os
import shutil

# Define source and destination directories
source_dir = "gender_balanced_audio_data/GBAD Dataset/GBAD Dataset"
destination_dir = "data"

# Define splits and categories
splits = {
    "01. Training": "train",
    "02. Validation": "validation",
    "03. Testing": "test"
}
categories = ["FAKE", "REAL"]

# Create target directories
for split in splits.values():
    for category in categories:
        os.makedirs(os.path.join(destination_dir, split, category.lower()), exist_ok=True)

print("Target directories are set up!")

# Move files to the new structure
for source_split, target_split in splits.items():
    for category in categories:
        source_category_path = os.path.join(source_dir, source_split, category)
        target_category_path = os.path.join(destination_dir, target_split, category.lower())

        if os.path.exists(source_category_path):
            files = [f for f in os.listdir(source_category_path) if f.endswith(".wav")]

            for file in files:
                src_file_path = os.path.join(source_category_path, file)
                dst_file_path = os.path.join(target_category_path, file)

                shutil.move(src_file_path, dst_file_path)

print("✅ Files have been successfully moved into the new structure!")

import os

# Define the base directory
base_dir = "data"

# Define the dataset splits
splits = ["train", "validation", "test"]
categories = ["fake", "real"]

# Count files in each directory
total_files = 0

for split in splits:
    print(f"\n📂 {split.upper()} SET:")
    for category in categories:
        category_path = os.path.join(base_dir, split, category)

        if os.path.exists(category_path):
            num_files = len([f for f in os.listdir(category_path) if f.endswith(".wav")])
            total_files += num_files
            print(f"   - {category}: {num_files} files")
        else:
            print(f"   - {category}: Directory not found!")

print(f"\n✅ Total number of files in dataset: {total_files}")

import os

def print_tree(directory, indent=""):
    print(indent + "|-- " + os.path.basename(directory))
    sub_dirs = [d for d in os.listdir(directory) if os.path.isdir(os.path.join(directory, d))]

    for i, sub_dir in enumerate(sorted(sub_dirs)):
        new_path = os.path.join(directory, sub_dir)
        new_indent = indent + ("|   " if i < len(sub_dirs) - 1 else "    ")
        print_tree(new_path, new_indent)

# Change 'data' to your target directory
base_dir = "data"
print_tree(base_dir)

# !pip install pydub

import os
from pydub import AudioSegment
from tqdm import tqdm

# Define source and destination paths
source_path = "data/"
destination_path = "preprocessed_data/"

# Define dataset splits and categories
splits = ["train", "validation", "test"]
categories = ["fake", "real"]

# Ensure destination folders exist
for split in splits:
    for category in categories:
        os.makedirs(os.path.join(destination_path, split, category), exist_ok=True)

# Target audio duration (15 seconds)
TARGET_DURATION_MS = 15000

def process_audio(src_file, dest_file):
    """Processes an audio file to ensure it's exactly 15 seconds."""
    try:
        audio = AudioSegment.from_wav(src_file)
        duration_ms = len(audio)

        if duration_ms < TARGET_DURATION_MS:
            silence = AudioSegment.silent(duration=TARGET_DURATION_MS - duration_ms)
            audio = audio + silence  # Pad with silence

        audio = audio[:TARGET_DURATION_MS]  # Trim to 15 seconds
        audio.export(dest_file, format="wav")
    except Exception as e:
        print(f"Error processing {src_file}: {e}")

# Process dataset
for split in splits:
    for category in categories:
        src_folder = os.path.join(source_path, split, category)
        dest_folder = os.path.join(destination_path, split, category)

        if not os.path.exists(src_folder):
            print(f"Skipping missing directory: {src_folder}")
            continue

        files = [f for f in os.listdir(src_folder) if f.endswith(".wav")]

        with tqdm(total=len(files), desc=f"Processing {split}/{category}", unit="file") as pbar:
            for idx, file_name in enumerate(files):
                src_file = os.path.join(src_folder, file_name)
                dest_file = os.path.join(dest_folder, f"{category}_{idx}.wav")
                process_audio(src_file, dest_file)
                pbar.update(1)

print("✅ Dataset restructuring and preprocessing completed!")

for split in ["train", "validation", "test"]:
    real_path = os.path.join(base_dir, split, "real")
    fake_path = os.path.join(base_dir, split, "fake")

    real_count = len(os.listdir(real_path)) if os.path.exists(real_path) else 0
    fake_count = len(os.listdir(fake_path)) if os.path.exists(fake_path) else 0

    print(f"{split.upper()} -> REAL: {real_count}, FAKE: {fake_count}")

import os
import librosa
import numpy as np
import soundfile as sf
from tqdm import tqdm

# Define paths
base_dir = "preprocessed_data"  # Your existing dataset directory
output_dir = "processed"  # Output directory for processed audio


# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

def preprocess_audio(file_path, target_duration=15.0, target_sr=44100, n_mfcc=40):
    """Preprocess an audio file for deepfake detection."""
    try:
        audio, sr = librosa.load(file_path, sr=None, mono=True)
    except Exception as e:
        print(f"Error loading {file_path}: {e}")
        return None, None

    # Resample if necessary
    if sr != target_sr:
        audio = librosa.resample(audio, orig_sr=sr, target_sr=target_sr)
        sr = target_sr

    # Ensure audio is exactly target_duration seconds
    target_length = int(target_duration * sr)
    if len(audio) < target_length:
        audio = np.pad(audio, (0, target_length - len(audio)), mode='constant')
    else:
        audio = audio[:target_length]

    # Normalize amplitude
    if np.max(np.abs(audio)) > 0:
        audio = audio / np.max(np.abs(audio))

    # Extract MFCC features
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=n_mfcc)
    return mfcc.T, sr  # Transpose to get (time_steps, n_mfcc)

# Process all files in the dataset
for split in ["train", "validation", "test"]:
    split_path = os.path.join(base_dir, split)
    output_split_path = os.path.join(output_dir, split)
    os.makedirs(output_split_path, exist_ok=True)

    for category in ["real", "fake"]:
        category_path = os.path.join(split_path, category)
        output_category_path = os.path.join(output_split_path, category)
        os.makedirs(output_category_path, exist_ok=True)

        # List all .wav files
        files = [f for f in os.listdir(category_path) if f.endswith(".wav")]

        # Use tqdm to track progress
        for file_name in tqdm(files, desc=f"Processing {split}/{category}", unit="file"):
            file_path = os.path.join(category_path, file_name)
            output_file_path = os.path.join(output_category_path, file_name.replace(".wav", ".npy"))

            # Preprocess audio and extract MFCC features
            mfcc_features, _ = preprocess_audio(file_path)
            if mfcc_features is not None:
                np.save(output_file_path, mfcc_features)  # Save the MFCC features

print("Preprocessing complete! All files are saved in 'preprocessed_data'.")

import torch
from torch.utils.data import Dataset
import numpy as np
import os

class AudioFeatureDataset(Dataset):
    def __init__(self, feature_dir, subset):
        """
        Args:
            feature_dir (str): Path to the directory containing preprocessed features.
            subset (str): One of 'train', 'validation', or 'test'.
        """
        self.feature_dir = os.path.join(feature_dir, subset)
        self.real_features = [os.path.join(self.feature_dir, "real", f) for f in os.listdir(os.path.join(self.feature_dir, "real")) if f.endswith(".npy")]
        self.fake_features = [os.path.join(self.feature_dir, "fake", f) for f in os.listdir(os.path.join(self.feature_dir, "fake")) if f.endswith(".npy")]
        self.file_paths = self.real_features + self.fake_features
        self.labels = [0] * len(self.real_features) + [1] * len(self.fake_features)

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        feature = np.load(self.file_paths[idx])
        label = self.labels[idx]
        return torch.tensor(feature, dtype=torch.float32), torch.tensor(label, dtype=torch.float32)

# import torch
# import torch.nn as nn

# class Attention(nn.Module):
#     def __init__(self, lstm_hidden_dim):
#         super(Attention, self).__init__()
#         self.attn = nn.Linear(lstm_hidden_dim * 2, 1)  # For bidirectional LSTM

#     def forward(self, lstm_output):
#         attn_weights = torch.softmax(self.attn(lstm_output), dim=1)  # Softmax over time
#         context = torch.sum(attn_weights * lstm_output, dim=1)  # Weighted sum
#         return context, attn_weights

# class BiLSTM_Attention(nn.Module):
#     def __init__(self, input_dim, hidden_dim=64, num_layers=2, num_classes=1):
#         super(BiLSTM_Attention, self).__init__()
#         self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers=num_layers,
#                             batch_first=True, bidirectional=True, dropout=0.2)
#         self.attention = Attention(hidden_dim)
#         self.fc1 = nn.Linear(hidden_dim * 2, 64)
#         self.fc2 = nn.Linear(64, 32)
#         self.fc3 = nn.Linear(32, num_classes)
#         self.dropout = nn.Dropout(0.2)
#         self.relu = nn.ReLU()
#         self.sigmoid = nn.Sigmoid()

#     def forward(self, x):
#         lstm_out, _ = self.lstm(x)  # (batch, seq_len, hidden_dim*2)
#         attn_out, attn_weights = self.attention(lstm_out)
#         x = self.relu(self.fc1(attn_out))
#         x = self.dropout(x)
#         x = self.relu(self.fc2(x))
#         x = self.dropout(x)
#         x = self.sigmoid(self.fc3(x))  # Binary output
#         return x

import torch
import torch.nn as nn

# Improved Attention Mechanism - Scaled Dot-Product Attention
class ScaledDotProductAttention(nn.Module):
    def __init__(self, hidden_dim):
        super(ScaledDotProductAttention, self).__init__()
        self.scale = torch.sqrt(torch.tensor(hidden_dim, dtype=torch.float32))
        self.softmax = nn.Softmax(dim=1)

    def forward(self, lstm_output):
        attn_scores = torch.bmm(lstm_output, lstm_output.transpose(1, 2)) / self.scale  # Scaled dot product
        attn_weights = self.softmax(attn_scores[:, :, -1])  # Take last step attention
        context = torch.sum(attn_weights.unsqueeze(2) * lstm_output, dim=1)  # Weighted sum
        return context, attn_weights

# Improved BiLSTM-Attention Model
class BiLSTM_Attention(nn.Module):
    def __init__(self, input_dim, hidden_dim=128, num_layers=3, num_classes=1, dropout_rate=0.3):
        super(BiLSTM_Attention, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        # BiLSTM Layer with Layer Normalization
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers=num_layers,
                            batch_first=True, bidirectional=True, dropout=dropout_rate)
        self.layer_norm = nn.LayerNorm(hidden_dim * 2)  # Normalize output

        # Scaled Dot-Product Attention
        self.attention = ScaledDotProductAttention(hidden_dim * 2)

        # Fully Connected Layers with Xavier Initialization
        self.fc1 = nn.Linear(hidden_dim * 2, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, num_classes)

        # Activation & Regularization
        self.leaky_relu = nn.LeakyReLU(0.1)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)  # (batch, seq_len, hidden_dim*2)
        lstm_out = self.layer_norm(lstm_out)  # Apply Layer Norm

        attn_out, attn_weights = self.attention(lstm_out)  # Apply Attention

        x = self.leaky_relu(self.fc1(attn_out))
        x = self.dropout(x)
        x = self.leaky_relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)  # No sigmoid here (for BCEWithLogitsLoss)

        return x  # Logits output (apply sigmoid during loss calculation)

# Weight Initialization Function
def init_weights(m):
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        nn.init.zeros_(m.bias)
    elif isinstance(m, nn.LSTM):
        for name, param in m.named_parameters():
            if "weight" in name:
                nn.init.xavier_uniform_(param)
            elif "bias" in name:
                nn.init.zeros_(param)

# Example Usage
if __name__ == "__main__":
    batch_size = 16
    seq_len = 30
    input_dim = 260  # Assuming 260 features per frame
    model = BiLSTM_Attention(input_dim=input_dim)
    model.apply(init_weights)  # Apply weight initialization

    sample_input = torch.randn(batch_size, seq_len, input_dim)  # (batch, seq_len, features)
    output = model(sample_input)
    print("Model Output Shape:", output.shape)  # Should be (batch_size, num_classes)


import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm

# Initialize datasets
train_dataset = AudioFeatureDataset("processed", "train")
val_dataset = AudioFeatureDataset("processed", "validation")
test_dataset = AudioFeatureDataset("processed", "test")

# Create DataLoaders with optimizations
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2, pin_memory=True)

# Initialize model, loss, and optimizer
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BiLSTM_Attention(input_dim=40).to(device)  # Change input_dim if necessary

criterion = nn.BCEWithLogitsLoss()  # More stable than BCELoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)  # AdamW helps with weight decay



import torch
from tqdm import tqdm

# Training loop parameters
num_epochs = 20
patience = 5
best_val_loss = float("inf")
epochs_without_improvement = 0

train_losses, val_losses = [], []
train_accuracies, val_accuracies = [], []

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    correct, total = 0, 0

    # Training phase
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs} [Training]")
    for waveforms, labels in progress_bar:
        waveforms, labels = waveforms.to(device), labels.to(device).float()  # Ensure labels are float for BCEWithLogitsLoss

        optimizer.zero_grad()
        outputs = model(waveforms).squeeze(1)  # Ensure correct shape
        loss = criterion(outputs, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # Prevent exploding gradients
        optimizer.step()

        running_loss += loss.item()
        preds = (torch.sigmoid(outputs) > 0.5).float()  # Apply sigmoid before thresholding
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        progress_bar.set_postfix(loss=loss.item(), acc=correct / total * 100)

    epoch_train_loss = running_loss / len(train_loader)
    epoch_train_acc = correct / total * 100
    train_losses.append(epoch_train_loss)
    train_accuracies.append(epoch_train_acc)

    # Validation phase
    model.eval()
    val_loss, val_correct, val_total = 0.0, 0, 0

    with torch.no_grad():
        progress_bar = tqdm(val_loader, desc=f"Epoch {epoch+1}/{num_epochs} [Validation]")
        for waveforms, labels in progress_bar:
            waveforms, labels = waveforms.to(device), labels.to(device).float()

            outputs = model(waveforms).squeeze(1)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            preds = (torch.sigmoid(outputs) > 0.5).float()
            val_correct += (preds == labels).sum().item()
            val_total += labels.size(0)

            progress_bar.set_postfix(loss=loss.item(), acc=val_correct / val_total * 100)

    epoch_val_loss = val_loss / len(val_loader)
    epoch_val_acc = val_correct / val_total * 100
    val_losses.append(epoch_val_loss)
    val_accuracies.append(epoch_val_acc)

    print(f"\nEpoch [{epoch+1}/{num_epochs}] | "
          f"Train Loss: {epoch_train_loss:.4f}, Train Acc: {epoch_train_acc:.2f}% | "
          f"Val Loss: {epoch_val_loss:.4f}, Val Acc: {epoch_val_acc:.2f}%")

    # Early stopping logic
    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        epochs_without_improvement = 0
        torch.save(model.state_dict(), "best_model.pth")  # Save best model for GPU
        torch.save(model.to("cpu").state_dict(), "best_model_cpu.pth")  # Save for CPU inference
        model.to(device)  # Move back to GPU if available
    else:
        epochs_without_improvement += 1
        if epochs_without_improvement >= patience:
            print("\nEarly stopping triggered. No improvement in validation loss.")
            break

print(len(train_losses), len(val_losses), num_epochs)

import matplotlib.pyplot as plt

# Plot Loss & Accuracy Graphs
plt.figure(figsize=(12, 5))

# Plot Loss
plt.subplot(1, 2, 1)
plt.plot(range(1, len(train_losses) + 1), train_losses, label="Train Loss", marker="o")
plt.plot(range(1, len(val_losses) + 1), val_losses, label="Validation Loss", marker="o")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss Over Epochs")
plt.legend()

# Plot Accuracy
plt.subplot(1, 2, 2)
plt.plot(range(1, len(train_accuracies) + 1), train_accuracies, label="Train Accuracy", marker="o")
plt.plot(range(1, len(val_accuracies) + 1), val_accuracies, label="Validation Accuracy", marker="o")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Accuracy Over Epochs")
plt.legend()

plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

import os
import torch

# Define path to save model in Google Drive
drive_path = "/content/drive/My Drive/audiomodels"
os.makedirs(drive_path, exist_ok=True)  # Create folder if it doesn't exist

# Save FULL model for both GPU and CPU
torch.save(model, os.path.join(drive_path, "best_model.pth"))  # GPU version
model.to("cpu")
torch.save(model, os.path.join(drive_path, "best_model_cpu.pth"))  # CPU version
model.to(device)  # Move back to GPU if available

print(f"Model saved in Google Drive at: {drive_path}")

import torch

# Load model from Google Drive
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_path = "/content/drive/My Drive/audiomodels/best_model.pth"  # Path in Drive
model = torch.load(model_path, map_location=device)
model.eval()  # Set to evaluation mode

print("Model loaded!")

import torch
from tqdm import tqdm

# Load the best model
model.load_state_dict(torch.load("best_model.pth", map_location=device))
model.to(device)
model.eval()  # Set model to evaluation mode

# Initialize test loss and accuracy tracking
test_loss, test_correct, test_total = 0.0, 0, 0

# Disable gradient calculation for testing
with torch.no_grad():
    progress_bar = tqdm(test_loader, desc="Testing Model")
    for waveforms, labels in progress_bar:
        waveforms, labels = waveforms.to(device), labels.to(device).float()

        # Forward pass
        outputs = model(waveforms).squeeze(1)
        loss = criterion(outputs, labels)

        # Track loss
        test_loss += loss.item()

        # Convert logits to binary predictions
        preds = (torch.sigmoid(outputs) > 0.5).float()
        test_correct += (preds == labels).sum().item()
        test_total += labels.size(0)

        # Update progress bar with metrics
        progress_bar.set_postfix(loss=loss.item(), acc=test_correct / test_total * 100)

# Compute average test loss and accuracy
avg_test_loss = test_loss / len(test_loader)
test_accuracy = test_correct / test_total * 100

print(f"\nTest Loss: {avg_test_loss:.4f}, Test Accuracy: {test_accuracy:.2f}%")

from google.colab import drive
drive.mount('/content/drive')



def extract_features(audio_path, sr=16000, n_mfcc=40, min_duration=15):
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"File not found: {audio_path}")

    y, sr = librosa.load(audio_path, sr=sr)  # Load audio
    required_length = sr * min_duration  # 15 seconds in samples

    # Ensure audio is at least 15 sec long
    if len(y) < required_length:
        y = np.pad(y, (0, required_length - len(y)), mode='constant')
    else:
        y = y[:required_length]  # Trim excess

    # Extract MFCC (shape: (n_mfcc, time_steps))
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
    mfcc = np.transpose(mfcc)  # Shape → (time_steps, n_mfcc)

    # Convert to tensor and return
    return torch.tensor(mfcc, dtype=torch.float32).unsqueeze(0).to(device)

def predict_audio(audio_path):
    feature = extract_features(audio_path)  # Extract features

    with torch.no_grad():
        output = model(feature).squeeze(1)  # Forward pass
        prediction = torch.sigmoid(output).item()  # Apply sigmoid

        label = "Fake" if prediction > 0.5 else "Real"
        confidence = prediction if prediction > 0.5 else 1 - prediction
        print(f"Prediction: {label} (Confidence: {confidence:.2f})")

audio_file = "/content/drive/MyDrive/audio_20250215_155434_clip_4.wav"
# audio_file = "/content/drive/MyDrive/notme.wav"
# audio_file = "/content/drive/MyDrive/videoplayback222.wav"
# audio_file = "/content/drive/MyDrive/v44.wav"

predict_audio(audio_file)

# from google.colab import files

# uploaded = files.upload()  # Opens file upload dialog

# audio_path = "/content/fakeaudio2.wav"  # Replace with the actual filename
# predict_audio(audio_path)

